name: Skill-Link Production Deploy

on:
  workflow_dispatch:  # push →　手動適用へ変更

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: process.env.AWS_ACCESS_KEY_ID
          aws-secret-access-key: process.env.AWS_SECRET_ACCESS_KEY
          aws-region: ap-northeast-1

      - name: Deploy (Dummy)
        run: echo "This is a configuration for manual deployment."
